import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1773879859889 implements MigrationInterface {
    name = 'InitialSchema1773879859889'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "oauth_connections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "provider" character varying NOT NULL, "providerId" character varying NOT NULL, "providerEmail" character varying NOT NULL, "accessToken" character varying, "refreshToken" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dd75e97352734560c9e585c057d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_965a16b0b673e786914af9910b" ON "oauth_connections" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_151f5cbe14a0a4d292e9f8ece5" ON "oauth_connections" ("provider", "providerId") `);
        await queryRunner.query(`CREATE TYPE "public"."service_catalog_category_enum" AS ENUM('HAIRCUT', 'HAIR_COLOR', 'HAIR_STYLING', 'HAIR_TREATMENT', 'BEARD_TRIM', 'SHAVE', 'MUSTACHE', 'MANICURE', 'PEDICURE', 'NAIL_ART', 'NAIL_EXTENSIONS', 'EVERYDAY_MAKEUP', 'SPECIAL_EVENT_MAKEUP', 'BRIDAL_MAKEUP', 'EYEBROW_SHAPING', 'EYELASH_EXTENSIONS', 'EYELASH_LIFT', 'FACIAL', 'FACIAL_TREATMENT', 'SKIN_CONSULTATION', 'RELAXING_MASSAGE', 'THERAPEUTIC_MASSAGE', 'CONSULTATION', 'PACKAGE_DEAL')`);
        await queryRunner.query(`CREATE TABLE "service_catalog" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "category" "public"."service_catalog_category_enum" NOT NULL, "defaultDuration" integer NOT NULL, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f2ba61b59fc13ea8e34acc75aa5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."employees_role_enum" AS ENUM('OWNER', 'COLLABORATOR')`);
        await queryRunner.query(`CREATE TABLE "employees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "businessId" uuid NOT NULL, "role" "public"."employees_role_enum" NOT NULL DEFAULT 'COLLABORATOR', "specialties" character varying, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_737991e10350d9626f592894ce" ON "employees" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3a6653569099ad4070c299403" ON "employees" ("businessId", "active") `);
        await queryRunner.query(`CREATE TABLE "employee_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employeeId" uuid NOT NULL, "businessServiceId" uuid NOT NULL, "customDuration" integer, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a505b513dfa83d93e9f61a8718f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0e1cfe638375478ede61a99b3f" ON "employee_services" ("employeeId", "active") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a9485f6241a95267116193dfd" ON "employee_services" ("businessServiceId", "active") `);
        await queryRunner.query(`CREATE TABLE "business_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "catalogServiceId" uuid NOT NULL, "customName" character varying, "customDescription" character varying, "price" numeric(10,2) NOT NULL, "duration" integer NOT NULL, "bufferBefore" integer NOT NULL DEFAULT '0', "bufferAfter" integer NOT NULL DEFAULT '0', "active" boolean NOT NULL DEFAULT true, "requirements" character varying, "isPopular" boolean NOT NULL DEFAULT false, "tags" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4b6dd7a4ce2532b6ad960b3d537" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7e650d3faf98bb9e152659155" ON "business_services" ("businessId", "active") `);
        await queryRunner.query(`CREATE TABLE "amenities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "icon" character varying NOT NULL, "description" character varying, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_8c5f9c7ff7e2174b53d4be10247" UNIQUE ("name"), CONSTRAINT "PK_c0777308847b3556086f2fb233e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "business_amenities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "amenityId" uuid NOT NULL, CONSTRAINT "PK_826b27ce9ff00b1dbb771ccd7f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9b85670aa7962659df3398c2d6" ON "business_amenities" ("businessId") `);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientId" uuid NOT NULL, "businessId" uuid NOT NULL, "bookingId" uuid NOT NULL, "rating" integer NOT NULL, "comment" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c357057587a1c2afae453515bf6" UNIQUE ("bookingId"), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8bf30713187361f910f8fb3c2c" ON "reviews" ("clientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d17ce9c119d29c7ec8c884044c" ON "reviews" ("businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."businesses_type_enum" AS ENUM('BARBER', 'NAIL_ARTIST', 'MAKEUP_ARTIST', 'HAIR_STYLIST', 'BEAUTY_SALON', 'BARBERSHOP', 'NAIL_SALON', 'SPA', 'LASH_ARTIST', 'BROW_ARTIST', 'SKINCARE_SPECIALIST', 'MASSAGE_THERAPIST')`);
        await queryRunner.query(`CREATE TYPE "public"."businesses_businesssize_enum" AS ENUM('INDIVIDUAL', 'SMALL_BUSINESS', 'MEDIUM_BUSINESS', 'LARGE_BUSINESS')`);
        await queryRunner.query(`CREATE TYPE "public"."businesses_servicemodality_enum" AS ENUM('PHYSICAL', 'HOME_SERVICE', 'BOTH')`);
        await queryRunner.query(`CREATE TABLE "businesses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ownerId" uuid NOT NULL, "businessName" character varying NOT NULL, "type" "public"."businesses_type_enum" NOT NULL, "businessSize" "public"."businesses_businesssize_enum" NOT NULL DEFAULT 'INDIVIDUAL', "description" character varying, "specialties" character varying, "verified" boolean NOT NULL DEFAULT false, "averageRating" numeric(3,2) NOT NULL DEFAULT '0', "totalReviews" integer NOT NULL DEFAULT '0', "cancellationHours" integer NOT NULL DEFAULT '24', "instantBooking" boolean NOT NULL DEFAULT false, "website" character varying, "instagram" character varying, "facebook" character varying, "address" character varying, "city" character varying, "lat" numeric(10,7), "lng" numeric(10,7), "serviceModality" "public"."businesses_servicemodality_enum" NOT NULL DEFAULT 'PHYSICAL', "serviceRadius" numeric(8,2), "serviceAreaLat" numeric(10,7), "serviceAreaLng" numeric(10,7), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_02e7bfb8e766e8e0ef449cc0f3" UNIQUE ("ownerId"), CONSTRAINT "PK_bc1bf63498dd2368ce3dc8686e8" PRIMARY KEY ("id")); COMMENT ON COLUMN "businesses"."serviceRadius" IS 'Radio de cobertura en km para servicios a domicilio'; COMMENT ON COLUMN "businesses"."serviceAreaLat" IS 'Punto central de cobertura (lat) para servicios a domicilio'; COMMENT ON COLUMN "businesses"."serviceAreaLng" IS 'Punto central de cobertura (lng) para servicios a domicilio'`);
        await queryRunner.query(`CREATE INDEX "IDX_9a2f08e67188581cea72b06cf5" ON "businesses" ("city") `);
        await queryRunner.query(`CREATE INDEX "IDX_85ccdffa40ffd1e009a84b64cd" ON "businesses" ("lat", "lng") `);
        await queryRunner.query(`CREATE TYPE "public"."booking_status" AS ENUM('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'FINALIZED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "booking_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bookingId" uuid NOT NULL, "previousStatus" "public"."booking_status" NOT NULL, "newStatus" "public"."booking_status" NOT NULL, "changedById" uuid NOT NULL, "reason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3bca51c9ed1c56768e390bac1aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ce3406e86937220091a1db7b8" ON "booking_history" ("bookingId") `);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientId" uuid NOT NULL, "businessId" uuid NOT NULL, "businessServiceId" uuid NOT NULL, "employeeId" uuid, "dateTime" TIMESTAMP NOT NULL, "status" "public"."booking_status" NOT NULL DEFAULT 'PENDING', "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ad439463e2eccd89d197e3b930" ON "bookings" ("updatedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_452d221731d9bee67bffeddc27" ON "bookings" ("employeeId", "dateTime") `);
        await queryRunner.query(`CREATE INDEX "IDX_85bdf1feb0ac43741650e7a438" ON "bookings" ("businessId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_40da42e381bfaf683b1108f3ea" ON "bookings" ("clientId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('CLIENT', 'BUSINESS_OWNER', 'EMPLOYEE', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "passwordHash" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'CLIENT', "emailVerified" boolean NOT NULL DEFAULT false, "emailVerificationToken" character varying, "emailVerificationExpiry" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7ad75a333a7bcf6a2b5d3517ca" ON "users" ("emailVerificationToken") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f5cbe00928ba4489cc7312573" ON "users" ("updatedAt") `);
        await queryRunner.query(`CREATE TABLE "profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "name" character varying NOT NULL, "avatarUrl" character varying, "phone" character varying, "address" character varying, "lat" numeric(10,8), "lng" numeric(11,8), "onboardingCompleted" boolean NOT NULL DEFAULT false, CONSTRAINT "REL_315ecd98bd1a42dcf2ec4e2e98" UNIQUE ("userId"), CONSTRAINT "PK_8e520eb4da7dc01d0e190447c8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."media_type_enum" AS ENUM('PROFILE_PHOTO', 'WORK_SAMPLE', 'BUSINESS_PHOTO', 'BUSINESS_COVER', 'DOCUMENT')`);
        await queryRunner.query(`CREATE TABLE "media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ownerId" uuid NOT NULL, "businessId" uuid, "employeeId" uuid, "type" "public"."media_type_enum" NOT NULL, "url" character varying NOT NULL, "filename" character varying NOT NULL, "mimeType" character varying NOT NULL, "size" integer NOT NULL, "altText" character varying, "caption" character varying, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f4e0fcac36e050de337b670d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_138d7762e76b7fee9de6db0f8e" ON "media" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_27405003f2b7c2398d0f08932a" ON "media" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e134e5766462769246e57819cc" ON "media" ("businessId") `);
        await queryRunner.query(`CREATE TABLE "client_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "clientId" uuid NOT NULL, "createdById" uuid NOT NULL, "content" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_50a5ba00f574738e3359f85956a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c06fefd9466119993d211f988e" ON "client_notes" ("businessId", "clientId") `);
        await queryRunner.query(`CREATE TABLE "cancellation_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "name" character varying NOT NULL, "description" text, "hoursBeforeBooking" integer NOT NULL, "penaltyPercentage" numeric(5,2) NOT NULL DEFAULT '0', "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_325e14a8f8003ef85146eecfc57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_exceptions_type_enum" AS ENUM('HOLIDAY', 'BREAK', 'CUSTOM')`);
        await queryRunner.query(`CREATE TABLE "schedule_exceptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid, "employeeId" uuid, "date" date NOT NULL, "type" "public"."schedule_exceptions_type_enum" NOT NULL, "startTime" TIME, "endTime" TIME, "reason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_829b77f6edcc7e36993664df455" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employee_schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employeeId" uuid NOT NULL, "dayOfWeek" integer NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "isWorking" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_d29891355bf2d67fc931a6e948f" UNIQUE ("employeeId", "dayOfWeek"), CONSTRAINT "PK_a82f7aa2134e860b889d1cf78b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "business_hours" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "dayOfWeek" integer NOT NULL, "openTime" TIME NOT NULL, "closeTime" TIME NOT NULL, "isOpen" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_405cd0afade77e0667449a2dc82" UNIQUE ("businessId", "dayOfWeek"), CONSTRAINT "PK_560a76077605005da835fe505a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "oauth_connections" ADD CONSTRAINT "FK_965a16b0b673e786914af9910b0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_737991e10350d9626f592894cef" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_c0a85906f3a73c2b47f7699bda8" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_services" ADD CONSTRAINT "FK_8798e0f72da4c393c44e8d3044b" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_services" ADD CONSTRAINT "FK_1fb55cbb7f37e93d540f1214bc7" FOREIGN KEY ("businessServiceId") REFERENCES "business_services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_services" ADD CONSTRAINT "FK_e5947796a4042ce27ff67e9e41b" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_services" ADD CONSTRAINT "FK_ca14175f49754299edcf401fe7a" FOREIGN KEY ("catalogServiceId") REFERENCES "service_catalog"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_amenities" ADD CONSTRAINT "FK_9b85670aa7962659df3398c2d63" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_amenities" ADD CONSTRAINT "FK_d472e7b2b96f822a209131844f6" FOREIGN KEY ("amenityId") REFERENCES "amenities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_8bf30713187361f910f8fb3c2c1" FOREIGN KEY ("clientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_d17ce9c119d29c7ec8c884044cb" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_c357057587a1c2afae453515bf6" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD CONSTRAINT "FK_02e7bfb8e766e8e0ef449cc0f36" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_history" ADD CONSTRAINT "FK_1ce3406e86937220091a1db7b86" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_history" ADD CONSTRAINT "FK_9984d11acebc37cebe4e148d19e" FOREIGN KEY ("changedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_ea203405627b9fb15023dd75661" FOREIGN KEY ("clientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bbf7fb08b638ef9eed30906515e" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_e03e6b863f9e34a6f37fdde5424" FOREIGN KEY ("businessServiceId") REFERENCES "business_services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_5415b42a6b8fd5e640e1b81f89a" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "FK_315ecd98bd1a42dcf2ec4e2e985" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_138d7762e76b7fee9de6db0f8eb" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_e134e5766462769246e57819cca" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_27405003f2b7c2398d0f08932a8" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_notes" ADD CONSTRAINT "FK_bbd77e3118c8297e0497b5de02d" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_notes" ADD CONSTRAINT "FK_4326d3a359321921d78fe82a142" FOREIGN KEY ("clientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_notes" ADD CONSTRAINT "FK_b359be5f18920f71cbcc0f9ced6" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cancellation_policies" ADD CONSTRAINT "FK_851978e978b25f7c84c64b471df" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_exceptions" ADD CONSTRAINT "FK_f7c6ead48e07eb87cda902ef654" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_exceptions" ADD CONSTRAINT "FK_2322fd1b084fb706adc6861bc9a" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_schedules" ADD CONSTRAINT "FK_4d5b29c922b0411a2a6c9e7c206" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_hours" ADD CONSTRAINT "FK_9f1fc24edcff686c3bc4d8fcb60" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "business_hours" DROP CONSTRAINT "FK_9f1fc24edcff686c3bc4d8fcb60"`);
        await queryRunner.query(`ALTER TABLE "employee_schedules" DROP CONSTRAINT "FK_4d5b29c922b0411a2a6c9e7c206"`);
        await queryRunner.query(`ALTER TABLE "schedule_exceptions" DROP CONSTRAINT "FK_2322fd1b084fb706adc6861bc9a"`);
        await queryRunner.query(`ALTER TABLE "schedule_exceptions" DROP CONSTRAINT "FK_f7c6ead48e07eb87cda902ef654"`);
        await queryRunner.query(`ALTER TABLE "cancellation_policies" DROP CONSTRAINT "FK_851978e978b25f7c84c64b471df"`);
        await queryRunner.query(`ALTER TABLE "client_notes" DROP CONSTRAINT "FK_b359be5f18920f71cbcc0f9ced6"`);
        await queryRunner.query(`ALTER TABLE "client_notes" DROP CONSTRAINT "FK_4326d3a359321921d78fe82a142"`);
        await queryRunner.query(`ALTER TABLE "client_notes" DROP CONSTRAINT "FK_bbd77e3118c8297e0497b5de02d"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_27405003f2b7c2398d0f08932a8"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_e134e5766462769246e57819cca"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_138d7762e76b7fee9de6db0f8eb"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "FK_315ecd98bd1a42dcf2ec4e2e985"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_5415b42a6b8fd5e640e1b81f89a"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_e03e6b863f9e34a6f37fdde5424"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bbf7fb08b638ef9eed30906515e"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_ea203405627b9fb15023dd75661"`);
        await queryRunner.query(`ALTER TABLE "booking_history" DROP CONSTRAINT "FK_9984d11acebc37cebe4e148d19e"`);
        await queryRunner.query(`ALTER TABLE "booking_history" DROP CONSTRAINT "FK_1ce3406e86937220091a1db7b86"`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP CONSTRAINT "FK_02e7bfb8e766e8e0ef449cc0f36"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_c357057587a1c2afae453515bf6"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_d17ce9c119d29c7ec8c884044cb"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_8bf30713187361f910f8fb3c2c1"`);
        await queryRunner.query(`ALTER TABLE "business_amenities" DROP CONSTRAINT "FK_d472e7b2b96f822a209131844f6"`);
        await queryRunner.query(`ALTER TABLE "business_amenities" DROP CONSTRAINT "FK_9b85670aa7962659df3398c2d63"`);
        await queryRunner.query(`ALTER TABLE "business_services" DROP CONSTRAINT "FK_ca14175f49754299edcf401fe7a"`);
        await queryRunner.query(`ALTER TABLE "business_services" DROP CONSTRAINT "FK_e5947796a4042ce27ff67e9e41b"`);
        await queryRunner.query(`ALTER TABLE "employee_services" DROP CONSTRAINT "FK_1fb55cbb7f37e93d540f1214bc7"`);
        await queryRunner.query(`ALTER TABLE "employee_services" DROP CONSTRAINT "FK_8798e0f72da4c393c44e8d3044b"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_c0a85906f3a73c2b47f7699bda8"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_737991e10350d9626f592894cef"`);
        await queryRunner.query(`ALTER TABLE "oauth_connections" DROP CONSTRAINT "FK_965a16b0b673e786914af9910b0"`);
        await queryRunner.query(`DROP TABLE "business_hours"`);
        await queryRunner.query(`DROP TABLE "employee_schedules"`);
        await queryRunner.query(`DROP TABLE "schedule_exceptions"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_exceptions_type_enum"`);
        await queryRunner.query(`DROP TABLE "cancellation_policies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c06fefd9466119993d211f988e"`);
        await queryRunner.query(`DROP TABLE "client_notes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e134e5766462769246e57819cc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27405003f2b7c2398d0f08932a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_138d7762e76b7fee9de6db0f8e"`);
        await queryRunner.query(`DROP TABLE "media"`);
        await queryRunner.query(`DROP TYPE "public"."media_type_enum"`);
        await queryRunner.query(`DROP TABLE "profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f5cbe00928ba4489cc7312573"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ad75a333a7bcf6a2b5d3517ca"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40da42e381bfaf683b1108f3ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85bdf1feb0ac43741650e7a438"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_452d221731d9bee67bffeddc27"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad439463e2eccd89d197e3b930"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ce3406e86937220091a1db7b8"`);
        await queryRunner.query(`DROP TABLE "booking_history"`);
        await queryRunner.query(`DROP TYPE "public"."booking_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85ccdffa40ffd1e009a84b64cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a2f08e67188581cea72b06cf5"`);
        await queryRunner.query(`DROP TABLE "businesses"`);
        await queryRunner.query(`DROP TYPE "public"."businesses_servicemodality_enum"`);
        await queryRunner.query(`DROP TYPE "public"."businesses_businesssize_enum"`);
        await queryRunner.query(`DROP TYPE "public"."businesses_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d17ce9c119d29c7ec8c884044c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8bf30713187361f910f8fb3c2c"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b85670aa7962659df3398c2d6"`);
        await queryRunner.query(`DROP TABLE "business_amenities"`);
        await queryRunner.query(`DROP TABLE "amenities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7e650d3faf98bb9e152659155"`);
        await queryRunner.query(`DROP TABLE "business_services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a9485f6241a95267116193dfd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e1cfe638375478ede61a99b3f"`);
        await queryRunner.query(`DROP TABLE "employee_services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3a6653569099ad4070c299403"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_737991e10350d9626f592894ce"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP TYPE "public"."employees_role_enum"`);
        await queryRunner.query(`DROP TABLE "service_catalog"`);
        await queryRunner.query(`DROP TYPE "public"."service_catalog_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_151f5cbe14a0a4d292e9f8ece5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_965a16b0b673e786914af9910b"`);
        await queryRunner.query(`DROP TABLE "oauth_connections"`);
    }

}
